### ISSUE TITLE
No candidate version available for opscode-push-jobs-server

### ISSUE THREAD

**Issue by andyrepton** [chef/chef-push#12]
Hey all, when trying to install on CentOS 7.1 I get the following error:

```
* yum_package[push-server] action install
                             * No candidate version available for opscode-push-jobs-server
                             ================================================================================
                             Error executing action `install` on resource 'yum_package[push-server]'
                             ================================================================================

                             Chef::Exceptions::Package
                             -------------------------
                             No candidate version available for opscode-push-jobs-server
```

This is me moving the issue from https://github.com/chef-cookbooks/delivery-cluster/issues/184 The package seems to be missing from the public repositories for el7 and needs to be added. The package can be installed from the el6 repositories in order to proceed.

**Comment by mmzyk** [comment]
Thanks @Seth-Karlo. We're aware of it because we've never official published CentOS 7 packages. We're planning to remedy that, but I don't have a solid time line for you.

**Comment by andyrepton** [comment]
Hey Mark,

Not to worry, I understand! I'm working on a temp fix that will fix my cluster rollouts, if I get it working I'll post it here.

Thanks,

Andy

**Comment by jordzn** [comment]
I am having this same issue with RHEL 7 and the chef-server cookbook as an add-on.  What is the timeline to get a RHEL7 push-jobs package available for the public to use?  Is push-jobs now in maintenance mode or are you planning to improve it and support new (and not that new) OS Platform versions?

**Comment by brentm5** [comment]
Any idea of when a centos 7 package will be created for the push jobs server?

**Comment by juliandunn** [comment]
Hello! Apologies for the delay -- there is a Push Jobs Server package now for EL7 platforms including CentOS, on downloads.chef.io.
